import angular from 'angular';

var drupalTug = angular.module('drupalTug',[]);

drupalTug.controller('envCtrl', function($scope) {

  var jf = require('jsonfile')
  var file = __dirname+'/config/env_variables.json'
  var out = jf.readFileSync(file);

$scope.env_variables = out;

  $scope.save = function() {
    // some kind of try/catch here?
    $scope.msg = 'Updated'

var obj = $scope.env_variables

jf.writeFileSync(file, obj)

// also write out a bash shell variable compatible file
var fs = require('fs');

var d = new Date();
var n = d.toISOString();
var outstring = '#!/bin/bash\n# Generated by electron ui on ' + n + '\n';

var arrayLength = obj.length;

for (var i = 0; i < arrayLength; i++) {
    outstring += obj[i]['name'] + '='


    console.log(obj[i]['name'])
    if(obj[i]['value']){
      outstring += '"' + obj[i]['value'] + '"'
    }
    outstring += '\n'
}

fs.writeFile(__dirname+'/config/env_variables.config', outstring, function (err) {
  if (err) {
    $scope.msg = 'Error'
    return console.log(err);
    }
});

  };
});
