import angular from 'angular';

var drupalTug = angular.module('drupalTug',[]);

drupalTug.controller('envCtrl', function($scope) {

  var jf = require('jsonfile')
  var file = __dirname+'/config/env_variables.json'
  var out = jf.readFileSync(file);

$scope.env_variables = out;

  $scope.save = function() {
    // some kind of try/catch here?
    $scope.msg = 'Updated'

var obj = $scope.env_variables

jf.writeFileSync(file, obj)

// also write out a bash shell variable compatible file
var fs = require('fs');

var d = new Date();
var n = d.toISOString();
var outstring = '#!/bin/bash\n# Generated by electron ui on ' + n + '\n';

var arrayLength = obj.length;

for (var i = 0; i < arrayLength; i++) {
    outstring += obj[i]['name'] + '='

    if(obj[i]['value']){
      outstring += '"' + obj[i]['value'] + '"'
    }
    outstring += '\n'
}

fs.writeFile(__dirname+'/config/env_variables.config', outstring, function (err) {
  if (err) {
    $scope.msg = 'Error'
    return console.log(err);
    }
});

  };
});

drupalTug.directive('electronDialog', function () {
    return {
      // use ngmodel to update the value
      require: 'ngModel',
      link: function ($scope, element, attrs, ctrl) {
            element.bind('click', function () {

              // use the native file selector
                var remote = require('remote');
                var dialog = remote.require('dialog');
                dialog.showOpenDialog({ properties: [ 'openFile']},function(selectedPath) {

                   if(selectedPath) {
                     // update the value in the view and model
                     ctrl.$setViewValue(selectedPath);
                     ctrl.$render();
                    }
                  })
                })
}}
ß});
